Fix build on MSVC, install headers, library, pkgconfig file
mesonbuild/libxml2 pull request #9
Opened 2018-11-30 22:01 UTC by nirbheek

Also build xmllint and install it

2018-12-03 17:11 UTC, sarum9in requested changes
It would also be nice to have `LICENSE.build` but if it is too much hassle to get the consent from other authors feel free to ignore.

2018-12-03 17:11 UTC, sarum9in commented on meson.build
> +                  install: true)
Looks like indentation broke here. Probably you should use spaces consistently.

2018-12-03 17:11 UTC, sarum9in commented on meson.build
>  				 dependencies: deps)
Same indentation problem.

2018-12-03 17:11 UTC, sarum9in commented on meson.build
>  		     dependencies : xml2lib_dep)
And once again, indentation.

2018-12-04 03:02 UTC, nirbheek commented
Updated, thanks for noticing the indentation issues!

I'm happy to license my work under the usually `LICENSE.build` used for wraps. CCing other contributors to get their permission too: @TingPing @roshbaby @talisein @jpakkane.

2018-12-04 03:30 UTC, TingPing commented
@nirbheek 	You have my permission to re-license my work.

2018-12-04 05:19 UTC, talisein commented
You have my permission to re-license my work

2018-12-04 16:12 UTC, sarum9in commented
FYI there was a blanket approval from Jussi for this license before for all his work on meson wraps.

2018-12-04 16:16 UTC, merged